services:
  clickhouse:
    image: 'clickhouse/clickhouse-server:25.3'
    container_name: clickhouse
    restart: unless-stopped
    ports:
      - '8123:8123'
      - '9000:9000'
    environment:
      - CLICKHOUSE_DB=default
      - CLICKHOUSE_USER=default
      - CLICKHOUSE_PASSWORD=
      - CLICKHOUSE_DEFAULT_ACCESS_MANAGEMENT=1
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    volumes:
      - 'chdata:/var/lib/clickhouse'
volumes:
  chdata: null
networks:
  peerdb_network:
    external: true
