version: '3.8'
services:
  grafana:
    image: 'grafana/grafana-oss:latest'
    container_name: grafana
    restart: unless-stopped
    ports:
      - '3001:3000'
    volumes:
      - 'grafana-data:/var/lib/grafana'
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=mude_essa_senha_forte
      - GF_USERS_ALLOW_SIGN_UP=false
      - GF_AUTH_ANONYMOUS_ENABLED=false
    networks:
      - monitoring
volumes:
  grafana-data: null
networks:
  monitoring:
    driver: bridge
