services:
  nifi:
    image: 'apache/nifi:latest'
    container_name: nifi
    hostname: anifi.tirusassessoria.com
    ports:
      - '8443:8443'
      - '8085:8085'
      - '9091:9091'
    environment:
      - NIFI_WEB_HTTPS_PORT=8443
      - SINGLE_USER_CREDENTIALS_USERNAME=admin
      - SINGLE_USER_CREDENTIALS_PASSWORD=610kL3thcS
    volumes:
      - 'nifi-database:/opt/nifi/nifi-current/database_repository'
      - 'nifi-logs:/opt/nifi/nifi-current/logs'
      - 'nifi-conf:/opt/nifi/nifi-current/conf'
      - 'nifi-nar-extensions:/opt/nifi/nifi-current/nar_extensions'
      - 'nifi-provenance:/opt/nifi/nifi-current/provenance_repository'
      - 'nifi-python-extensions:/opt/nifi/nifi-current/python_extensions'
      - 'nifi-state:/opt/nifi/nifi-current/state'
      - 'nifi-content:/opt/nifi/nifi-current/content_repository'
      - 'nifi-flowfile:/opt/nifi/nifi-current/flowfile_repository'
      - '/opt/nifi-drivers/postgresql-42.7.4.jar:/opt/nifi/nifi-current/drivers/postgresql-42.7.4.jar:ro'
      - '/opt/nifi-drivers/clickhouse-jdbc-0.6.4-shaded.jar:/opt/nifi/nifi-current/drivers/clickhouse-jdbc-0.6.4-shaded.jar:ro'
    restart: unless-stopped
volumes:
  nifi-database: null
  nifi-logs: null
  nifi-conf: null
  nifi-nar-extensions: null
  nifi-provenance: null
  nifi-python-extensions: null
  nifi-state: null
  nifi-content: null
  nifi-flowfile: null
