services:
  postgres:
    image: 'timescale/timescaledb:latest-pg16'
    container_name: postgres-ts
    restart: unless-stopped
    environment:
      POSTGRES_DB: app
      POSTGRES_USER: app
      POSTGRES_PASSWORD: supersecret123
    command: "postgres -c wal_level=logical\n         -c max_replication_slots=10\n         -c max_wal_senders=10\n         -c shared_preload_libraries=timescaledb\n"
    ports:
      - '5432:5432'
    volumes:
      - 'pgdata:/var/lib/postgresql/data'
    healthcheck:
      test:
        - CMD-SHELL
        - 'pg_isready -U app -d app'
      interval: 10s
      timeout: 5s
      retries: 5
volumes:
  pgdata: null
